apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
      - master
jobs:
  build:
    steps:
      - uses: docker://maven:3-eclipse-temurin-17
        name: Maven Build
        shell: sh
        run: mvn clean verify -
